[config]
default_to_workspace = false

[tasks.format]
dependencies = []
command = "cargo"
args = ["fmt"]

[tasks.clippy]
dependencies = []
command = "cargo"
args = [
    "clippy",
    "--target=nvptx64-nvidia-cuda.json",
    "-Z", "build-std=core,alloc",
]

[tasks.kernel]
toolchain = "nightly"
command = "cargo"
args = [
    "rustc",
    "--release",
    "--bin=kernel",
    "--target=nvptx64-nvidia-cuda.json",
    "-Z", "build-std=core,alloc",
    "--",
    "-Cllvm-args=--nvptx-fma-level=2",
    "-Cllvm-args=--nvptx-prec-divf32=0",
    "-Cllvm-args=--nvptx-sched4reg",
    "-Cllvm-args=--mul-constant-optimization",
    "--emit=asm=montey/kernel.ptx,llvm-ir=kernel.ll",
    "-Cdebuginfo=0",
    "-Copt-level=3",
    "-Clto",
    "-Cembed-bitcode=yes",
    "-Ctarget-cpu=sm_52",
    "-Ctarget-feature=+ptx60",
    "-Clinker=echo",
    "-Z", "no-link",
    "-Z", "combine_cgu",
]

[tasks.verify-kernel]
dependencies = ["kernel"]
command = "ptxas"
args = ["-v", "-arch=sm_52", "-e", "pencil", "-e", "layered_pencil", "-e", "axial_pencil", "-e", "layered_axial_pencil", "-e", "layered_free_space_pencil", "montey/kernel.ptx"]

[tasks.flow-build]
dependencies = [
    "format",
    "kernel",
]

[tasks.flow-develop]
dependencies = [
    "format",
    "kernel",
    "verify-kernel",
]
