[config]
default_to_workspace = false

[tasks.format]
dependencies = []
command = "cargo"
args = ["fmt"]

[tasks.clippy]
dependencies = []
command = "cargo"
args = [
    "clippy",
    "--target=nvptx64-nvidia-cuda.json",
    "-Z", "build-std=core,alloc",
    "-Z", "features=all",
]

[tasks.build-kernel]
toolchain = "nightly"
command = "cargo"
args = [
    "rustc",
    "--release",
    "--bin=kernel",
    "--target=nvptx64-nvidia-cuda.json",
    "-Z", "build-std=core,alloc",
    "-Z", "features=all",
    "--",
#    "-Cllvm-args=--nvptx-sched4reg",
#    "-Cllvm-args=--instcombine-code-sinking=false",
#    "-Cllvm-args=--instcombine-negator-enabled=true",
    "-Csave-temps",
    "--emit=asm=montey/kernel.ptx,llvm-ir=kernel.ll",
    "-Cdebuginfo=0",
    "-Copt-level=3",
#    "-Ccodegen-units=1",
    "-Clto",
    "-Cembed-bitcode=yes",
    "-Ctarget-cpu=sm_52",
    "-Ctarget-feature=+ptx60",
    "-Clinker=echo",
    "-Z", "no-link",
    "-Z", "mir-opt-level=3",
    "-Z", "combine_cgu",
]

[tasks.fix-kernel]
command = "python3"
args = [ "fix_ptx.py" ]

[tasks.kernel]
dependencies = [ "build-kernel", "fix-kernel" ]

[tasks.verify-kernel]
dependencies = ["kernel"]
command = "ptxas"
args = ["-v", "-arch=sm_52", "montey/kernel.ptx"]

[tasks.flow-build]
dependencies = [
    "format",
    "kernel",
]

[tasks.flow-develop]
dependencies = [
    "format",
    "kernel",
    "verify-kernel",
]
