edition = "2021"
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
max_width = 120
# fn_args_layout = "Vertical"
fn_single_line = true
format_macro_matchers = true
format_strings = true
match_arm_blocks = false
match_block_trailing_comma = true
imports_granularity = "Crate"
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
report_fixme = "Always"
report_todo = "Always"
use_field_init_shorthand = true
wrap_comments = true